---
name: autofix.ci
on: pull_request
permissions: {}
jobs:
  autofix:
    runs-on: ubuntu-24.04
    permissions: {}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          ref: ${{github.head_ref}}
          persist-credentials: false
      - uses: aquaproj/aqua-installer@82d0e83878a8657c4a6f2ff1755d3bfbfc67f329 # v4.1.0
        with:
          aqua_version: v2.63.0
      - run: aqua upc -prune
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
      - uses: suzuki-shunsuke/autofixci-action@989fe99ca39af1980b3515837570511eea7c6285 # v1.3.2-2
